# Stage 1: Build Angular app
FROM node:20-alpine AS build

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm install

# Копирование исходников
COPY . .

# Сборка проекта
RUN npm run build -- --configuration production --output-path=dist/frontend

# Stage 2: Запуск на nginx
FROM nginx:alpine

# Копируем статику в Nginx
COPY --from=build /app/dist/frontend /usr/share/nginx/html

# (Необязательно) Кастомный конфиг Nginx — если нужен SPA fallback
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
