version: '3'
services:
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:8.8.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      # Elasticsearch 8.x has HTTPS and auth on by default. This option is
      # needed to use HTTP and no auth (as used in the tests).
      - xpack.security.enabled=false
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    hostname: kibana
    image: kibana:8.8.2
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    networks:
      - elk

  prometheus: 
    image: prom/prometheus:v2.30.3
    ports: 
     - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped
    networks:
      - elk

  grafana:
    image: grafana/grafana:8.1.3
    user: "1000:1000"
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    env_file: 
      .env
    networks:
      - elk
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ambition-db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - elk
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "2g"

  backend: 
    hostname: ambition-back
    container_name: ambition-back
    build: 
      context: ./
    restart: unless-stopped
    depends_on:
      - postgres
      - elasticsearch
      - prometheus
    environment:
      - ES_HOST=elasticsearch
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
    volumes: 
      - ./uploads:/app/uploads
    networks:
      - elk

networks:
  elk: 
    driver: bridge

volumes: 
  elasticsearch: