pipeline {
    agent any

    parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Ветка для деплоя')
    }

    environment {
        DOTENV = credentials('onebiz-dotenv')
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: "*/${params.GIT_BRANCH}"]],
                        userRemoteConfigs: [[
                            url: 'https://github.com/PNik1ta/OneBiz',
                            credentialsId: 'github-token'
                        ]]
                    ])
                }
            }
        }

        stage('Write .env') {
            steps {
                script {
                    writeFile file: 'backend/.env', text: "${DOTENV}"
                }
            }
        }

        stage('Fix volume permissions') {
            steps {
                sh '''
                sudo chown -R jenkins:jenkins "$WORKSPACE/backend/postgres-data" || true
                sudo chmod -R u+rw "$WORKSPACE/backend/postgres-data" || true
                '''
            }
        }   

        stage('Kill process on 9090') {
            steps {
                sh '''
                PID=$(lsof -ti tcp:9090) || true
                if [ ! -z "$PID" ]; then
                  echo "Killing process on port 9090: $PID"
                  kill -9 $PID
                fi
                '''
            }
        }


        stage('Restart Containers') {
            steps {
                script {
                    sh "docker compose -f \"$WORKSPACE/backend/docker-compose.yml\" down"
                    sh "docker compose -f \"$WORKSPACE/backend/docker-compose.yml\" up -d --build"
                }
            }
        }
    }

    post {
        success { echo "✅ Деплой прошёл успешно" }
        failure { echo "❌ Ошибка при деплое" }
    }
}
