pipeline {
    agent any

    parameters {
        string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Ветка для деплоя')
    }

    environment {
        DOTENV = credentials('onebiz-dotenv')
    }

    stages {
        stage('Checkout Code') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: "*/${params.GIT_BRANCH}"]],
                        userRemoteConfigs: [[
                            url: 'https://github.com/PNik1ta/OneBiz',
                            credentialsId: 'github-token'
                        ]]
                    ])
                }
            }
        }

        stage('Write .env') {
            steps {
                script {
                    writeFile file: 'backend/.env', text: "${DOTENV}"
                }
            }
        }

        stage('Fix volume permissions') {
            steps {
                sh '''
                sudo chmod -R 777 "$WORKSPACE/backend/postgres-data" || true
                '''
            }
        }

        stage('Kill containers on 9090') {
            steps {
                sh '''
                CONTAINER=$(docker ps -q --filter "publish=9090") || true
                if [ ! -z "$CONTAINER" ]; then
                    echo "⚠️ Killing container on port 9090: $CONTAINER"
                    docker kill $CONTAINER || true
                fi
                '''
            }
        }

        stage('Kill process on port 9090') {
            steps {
                sh '''
                PIDS=$(sudo lsof -ti :9090) || true
                if [ ! -z "$PIDS" ]; then
                    echo "🎯 Killing processes on port 9090: $PIDS"
                    for pid in $PIDS; do
                        sudo kill -9 $pid || echo "⚠️ Failed to kill $pid (maybe already dead)"
                    done
                else
                    echo "✅ No process on port 9090"
                fi
                '''
            }
        }


        stage('Restart Containers') {
            steps {
                script {
                    sh "docker compose -f \"$WORKSPACE/backend/docker-compose.yml\" down"
                    sh "docker compose -f \"$WORKSPACE/backend/docker-compose.yml\" up -d --build"
                }
            }
        }
    }

    post {
        success { echo "✅ Деплой прошёл успешно" }
        failure { echo "❌ Ошибка при деплое" }
    }
}
